#!/usr/bin/env bash

function run_check(){
    tox -e $1
    if [ "$?" = "1" ]
    then
        echo "$1 check failed."
        exit 1
    fi
}

make clean

tomte check-code
tomte check-security
tomte check-copyright --author valory --exclude-part connections --exclude-part contracts --exclude-part protocols --exclude-part abstract_abci --exclude-part abstract_round_abci --exclude-part registration_abci --exclude-part reset_pause_abci --exclude-part termination_abci --exclude-part transaction_settlement_abci
run_check check-abciapp-specs
run_check check-packages
run_check check-hash